#ifndef COORDINATECALCULATIONCLASS_GLOBAL_H
#define COORDINATECALCULATIONCLASS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COORDINATECALCULATIONCLASS_LIBRARY)
#  define COORDINATECALCULATIONCLASS_EXPORT Q_DECL_EXPORT
#else
#  define COORDINATECALCULATIONCLASS_EXPORT Q_DECL_IMPORT
#endif

#endif // COORDINATECALCULATIONCLASS_GLOBAL_H
