#ifndef CLASSOFWORKWITHNMEA0183_GLOBAL_H
#define CLASSOFWORKWITHNMEA0183_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CLASSOFWORKWITHNMEA0183_LIBRARY)
#  define CLASSOFWORKWITHNMEA0183_EXPORT Q_DECL_EXPORT
#else
#  define CLASSOFWORKWITHNMEA0183_EXPORT Q_DECL_IMPORT
#endif

#endif // CLASSOFWORKWITHNMEA0183_GLOBAL_H
